---
- name: Playbook to configure Postgres
  hosts: postgres
  become: true
  vars:
    base_disk: /dev/sdb
    base_vg_name: vgpg
    base_lv_name: lvpg
    base_lv_fstype: xfs
    base_lv_mntpt: /dbs
    clair_disk: /dev/sdc
    clair_vg_name: vgclair
    clair_lv_name: lvclair
    clair_lv_fstype: xfs
    clair_lv_mntpt: "{{ base_lv_mntpt }}/clair"
    clair_db_cluster_name: clair
    clair_db_cluster_port: 5432
    quay_disk: /dev/sdd
    quay_vg_name: vgquay
    quay_lv_name: lvquay
    quay_lv_fstype: xfs
    quay_lv_mntpt: "{{ base_lv_mntpt }}/quay"
    quay_db_cluster_name: quay
    quay_db_cluster_port: 15432
  roles:
    - role: rthar_pg_base
      rthar_pg_base_disk_dev: "{{ base_disk }}"
      rthar_pg_base_vg_name: "{{ base_vg_name }}"
      rthar_pg_base_lv_name: "{{ base_lv_name }}"
      rthar_pg_base_lv_fstype: "{{ base_lv_fstype }}"
      rthar_pg_base_lv_mntpt: "{{ base_lv_mntpt }}"

    - role: rthar_pg_cluster
      rthar_pg_cluster_disk_dev: "{{ clair_disk }}"
      rthar_pg_cluster_vg_name: "{{ clair_vg_name }}"
      rthar_pg_cluster_lv_name: "{{ clair_lv_name }}"
      rthar_pg_cluster_lv_fstype: "{{ clair_lv_fstype }}"
      rthar_pg_cluster_lv_mntpt: "{{ clair_lv_mntpt }}"
      rthar_pg_cluster_name: "{{ clair_db_cluster_name }}"
      rthar_pg_cluster_port: "{{ clair_db_cluster_port }}"
      rthar_pg_cluster_manage_disks: true

    - role: rthar_pg_cluster
      rthar_pg_cluster_disk_dev: "{{ quay_disk }}"
      rthar_pg_cluster_vg_name: "{{ quay_vg_name }}"
      rthar_pg_cluster_lv_name: "{{ quay_lv_name }}"
      rthar_pg_cluster_lv_fstype: "{{ quay_lv_fstype }}"
      rthar_pg_cluster_lv_mntpt: "{{ quay_lv_mntpt }}"
      rthar_pg_cluster_name: "{{ quay_db_cluster_name }}"
      rthar_pg_cluster_port: "{{ quay_db_cluster_port }}"
      rthar_pg_cluster_manage_disks: true
